strain_id_field: "Seq_ID"
display_strain_field: "strain"

datasets:
  nextclade: "../nextclade_dataset/resources/nc_dataset/"
  backbone: "resources/backbone/"
  austrakka: "resources/example/"

threads:
  nextclade: 8
  align: 8
  tree: 8

iqtree_model: "HKY+G"

filter:
  exclude: "config/exclude.txt"
  min_length: 10000

traits:
  sampling_bias_correction: '3'
  traits_columns:
    gt1: 'Country region Host'
    gt2: 'Country region Host'
    gt3: 'Country region Host'
    gt4: 'Country region Host'
    gt5: 'Country region Host'

# from 
# https://www.biorxiv.org/content/10.1101/2024.03.27.586903v2
clockrate:
  gt1: "4.13e-4"
  gt2: "2.41e-4"
  gt3: "6.17e-5"
  gt4: "2.41e-4"
  gt5: "2.41e-4"