from snakemake.utils import min_version
from pathlib import Path

configfile: "config/config.yaml"
include: "rules/common.smk"

GENOTYPES = ['1', '2', '3', '4', '5']
OUTDIR = Path("output")
RESOURCES = Path("resources")

FETCH = check_ncbi_uploaded()

if FETCH:
    RULES = [        
        OUTDIR / "data" / "sequences.ndjson",
        OUTDIR / "results" / "metadata.tsv",
        OUTDIR / "results" / "austrakka.csv",
        OUTDIR / "results" / "sequences.fasta",
        expand(OUTDIR / "results" / "by_genotype" / "jev_gt{genotype}.fasta", genotype=GENOTYPES),
        expand(OUTDIR / "results" / "by_genotype" / "jev_gt{genotype}.tsv", genotype=GENOTYPES),
        ]
else:
    RULES = OUTDIR / "data" / "checked.txt"

rule all:
    input:
        RULES

include: "rules/fetch_from_ncbi.smk"
include: "rules/curate.smk"
include: "rules/qc_split.smk"