from pathlib import Path

configfile: "config/config.yaml"

GENOTYPES = ['1', '2', '3', '4', '5']
OUTDIR = Path("output")

rule all:
    input:
        expand(OUTDIR / "auspice" / "jev{genotype}.json", genotype=GENOTYPES),

include: "rules/prepare_sequences.at.smk"
include: "rules/construct_phylogeny.smk"
include: "rules/annotate_phylogeny.smk"
include: "rules/export.smk"

rule clean:
    message: "Removing directories: {params}"
    params:
        "results",
        "auspice"
    shell:
        "rm -rfv {params}"
